### PR TITLE
Release 7.1.0

### LINKED ISSUE #154: Filipino translations don't always work on sf.gov
The [Filipino translation](https://sf.gov/fil/node/1072) of [this form](https://sf.gov/node/1072) is unreliable. It's hard to tell what's going on, but I think it's a timing problem or race condition with the language detection in this theme. Observations:

- The translations appear _not_ to work the "first" load (with a cold cache?), but then work on subsequent refreshes.
- The `lang="fil"` attribute is stable: it's served from Drupal that way and remains unchanged after Google Translate loads.

I'd like to figure out how to write a failing test for this before trying to figure out a fix, since there are a lot of moving pieces.

### LINKED ISSUE #161: The "language" option is overridden by DOM lang attributes
I ran into this trying to get the new shared components example in #160 to respect the `language` option from the query string. The problem is that if any element above the form in the DOM has a `lang` attribute, its value overrides the `language` option passed in explicitly to the form constructor.

This example would alert "en" rather than "zh":

```html
<html lang="en">
  <div id="form"></div>
  <!-- formio.js + formio-sfds here -->
  <script>
    Formio.createForm(document.getElementById('form'), 'https://sfds.form.io/foo', {
      language: 'zh'
    }).then(form => alert(form.options.language))
  </script>
</html>
```

### PR DESCRIPTION
**Pull request by shawnbot**
👉 **This started in #156 as a patch release, but with a new feature in #146 I've decided to make it a minor release.**

## Pull requests
- [x] #155 Force form redraws when (re-)setting the language
- [x] #158 Add error messages example form
- [x] #159 Add lang option to proxy preview, etc.
- [x] #157 Bump ini (via @dependabot)
- [x] #146 Support "embedded" component translations
- [x] #160 Add shared components example

### :rocket: Features
- Components can now "embed" translations of labels and other text content via custom properties. See #146 for more information. (This is an experimental feature, hence the minor version bump.)

### :bug: Bug fixes
- Fixes #154 
- Fixes #161

### 🏠 Internal
- Add `lang` query string parameter support to the proxy preview API in #159 
- Add `FormioSFDS.version` export to the browser JS in #159 + #161
- Add `FormioSFDS.options` as a way to set option defaults on all of our forms at runtime
- Add support for form option overrides via the query string in examples in #161
- Hide example-related JS bundles from the size report in 7a79666

### CODE REVIEW

File: src/patch.js [hunk 1]
```diff
@@ -29,8 +30,10 @@ const defaultEvalContext = {
     const { type, key = type } = component
     return key ? this.t([
       `${key}.${field}`,
+      // this is the "legacy" naming scheme
       `${key}_${field}`,
-      component[field] || defaultValue || ''
+      `component.${type}.${field}`,
```
Comment (shawnbot) [inline src/patch.js:35]: The idea with this additional key was to make it possible to have translations for all components of a certain _type_: for instance if we wanted to standardize labels and error messages for, say, all email fields. This would make it possible to localize "ZIP code" across all of our forms without having to "upgrade" all of the existing zip code fields with embedded translations (see #146), or update translations of "ZIP code" in all of the form Phrase projects, bump the versions in each, etc.

For example, say we standardized on a custom `zipCode` component and wanted to translate its labels across all projects, we would add a `component.zipCode.label` key to the "form.io generic strings" Phrase project and keep it synced to this repo. This would take precedent over the label provided in the form.io editor, but _not_ over any project-specific translations of `{key}.label`.

File: src/patch.js [hunk 2]
```diff
@@ -29,8 +30,10 @@ const defaultEvalContext = {
...
+      dot.get(component, field) || defaultValue || ''
```
Comment (shawnbot) [inline src/patch.js:36]: This change makes it possible to access nested properties, e.g. `validate.customMessage`. Previously, that would fail because the code was trying to access `component['validate.customMessage']` rather than `component.validate.customMessage`.
